apiVersion: v1
kind: ServiceAccount
metadata:
  name: apic-secrets-prereq
  namespace: {{ .Values.apic.namespace }}
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: access-secrets-for-agent-mesh-secrets-creation
  namespace: {{ .Values.apic.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create

---  

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apic-prereq-to-secrets
  namespace: {{ .Values.apic.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-secrets-for-agent-mesh-secrets-creation
subjects:
- kind: ServiceAccount
  name: apic-secrets-prereq
  namespace: {{ .Values.apic.namespace }}

---  

apiVersion: batch/v1
kind: Job
metadata:
  name: apic-secrets-prereq
  namespace: {{ .Values.apic.namespace }}
spec:
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: apic-secrets-prereq
    spec:
      serviceAccountName: apic-secrets-prereq
      containers:
      - name: secret-init
        image: asayah/kubectl
        command:
        - sh
        - -c
        - |
          mkdir -p /tmp/sda
          mkdir -p /tmp/csa
          openssl genpkey -algorithm RSA -out /tmp/sda/private_key.pem -pkeyopt rsa_keygen_bits:2048
          openssl rsa -pubout -in /tmp/sda/private_key.pem -out /tmp/sda/public_key.der -outform der && base64 /tmp/sda/public_key.der > /tmp/sda/public_key
          openssl genpkey -algorithm RSA -out /tmp/csa/private_key.pem -pkeyopt rsa_keygen_bits:2048
          openssl rsa -pubout -in /tmp/csa/private_key.pem -out /tmp/csa/public_key.der -outform der && base64 /tmp/csa/public_key.der > /tmp/csa/public_key
          kubectl create secret generic csa-secrets --from-file=publicKey=/tmp/csa/public_key --from-file=privateKey=/tmp/csa/private_key.pem --from-literal=password="" -o yaml
          kubectl create secret generic sda-secrets --from-file=publicKey=/tmp/sda/public_key --from-file=privateKey=/tmp/sda/private_key.pem --from-literal=password="" -o yaml

      restartPolicy: Never
---